function r = optexp5(Tc, Ta, dt, Ri, Re, betas, alphag, n, mu, Ls, ps, pg) 
	r = Ta - 3*(Ri - dt)./(Re^3 - Ri^3) * (Tc * ( dt^2 * (dt-Re)/(dt-Ri) - dt*(dt-Re)^2/(dt-Ri) ...
	    + (dt - Re)^3/(3*(dt-Ri)) - dt*Ri - (dt-Ri)^2/3 ) + (dt - Ri) * mu * Ri*betas/(3*alphag*n*Ls) * (ps - pg)* (2*dt*(dt-Ri)/(n+2) ...
	    - dt^2/(n+1) - (dt-Ri)^2/(n+3)) );
end
