function r = optexp_new(Tc, Ta, dtbl, dt, Ri, Rim1, Re, betas, n, Ls)
	r =  - Ta + Tc .* ( (dtbl.^3 - Ri.^3)./(Re.^3 - Ri.^3) - (dtbl.^3 - Ri.^3).*dtbl./((Re.^3 - Ri.^3).*(dtbl - Ri)) ...
		+ 3/4 .* (dtbl.^4 - Ri.^4)./( ( Re.^3 - Ri.^3) .* (dtbl.^3 - Ri.^3) ) )  + TI2(Tc, dtbl, Ri, Rim1, betas, n, Ls, dt) .*...
	       	( (dtbl.^3 - Ri.^3).*dtbl./((Re.^3 - Ri.^3).*(dtbl - Ri)) - 3/4 .* (dtbl.^4 - Ri.^4)./( ( Re.^3 - Ri.^3) .* (dtbl.^3 - Ri.^3) ) );
end	
